.node-template:
  image: node:22
  before_script:
    - corepack enable

include:
  - local: .gitlab/workflows/tests.yml
  - local: .gitlab/workflows/build.yml
  - local: .gitlab/workflows/deploy.yml
