minimumReleaseAge: 1440

shellEmulator: true

strictPeerDependencies: true

trustPolicy: no-downgrade

ignoredBuiltDependencies:
  - core-js
  - unrs-resolver

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi
