minimumReleaseAge: 1440
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43830
strictPeerDependencies: true

ignoredBuiltDependencies:
  - core-js
  - unrs-resolver

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi
minimumReleaseAgeExclude:
  # Renovate security update: vitest@4.1.0
  - vitest@4.1.0
